更新CI kah 詞表來源
i3thuan5/kau3-tian2_iong7-ji7 pull request #68
Opened 2023-06-27 08:57 UTC by sih4sing5hong5

## 需求
欲加 thái-ko ê「ko」漢字，本底這PR按算先修CI就好，毋過本底教典github ê`詞目總檔屬性無去--ah，所以就sūn-suà更新用字來源。

CI畫面：
![圖片](https://github.com/i3thuan5/KauTian-IongJi/assets/5996555/9e4396b4-35ae-4abb-9a4f-56202bb27d62)

Github無去：
![圖片](https://github.com/i3thuan5/KauTian-IongJi/assets/5996555/19447c5d-4477-40b0-9ada-3f3b7b124fea)

## 變更時間
2023.6.28～2023.6.30

## 做法

- 自新教典lia̍h ods詞表。
- 因為名姓已經kap入去教典，就取消`教典名姓` kah `甘字典`

## 影響

### 機密

Bô。

### 完整

Bô。

### 可用

- `教典名姓` kah `甘字典`，印象無專案有用這。

## 解決做法Github連結

這PR。

## 未來規劃

毋免用著KangKu kah 分詞。

### 審查意見

2023-06-28 03:21 UTC, sih4sing5hong5 reviewed
巡過

2023-06-29 06:18 UTC, sih4sing5hong5 reviewed
巡過

2023-06-30 01:54 UTC, a8568730 requested changes
勞煩

2023-06-30 01:54 UTC, a8568730 commented on tox.ini
>      coverage run --source=用字 -m unittest discover -s 試驗/教典名姓
`試驗/教典名姓` 這應該毋免巡--ah。

2023-06-30 01:54 UTC, a8568730 commented on 教典/匯入資料.py
> +        yield '𰹬', 'tsn̄g'
咱這部份另外用檔案管理較好，紀錄字漢字、字羅馬字、收錄理由、收錄決議時間。

2023-06-30 01:54 UTC, a8568730 commented on 教典/匯入資料.py
> +            if mia not in ['詞目', '又唸作', '合音唸作', '俗唸作', '詞彙比較', '名']:
無按算加`姓`？

2023-06-30 01:54 UTC, a8568730 commented on 教典/匯入資料.py
> +                        tsua[hanjiui] not in ['兔', '𠕆', ] and
欲踢ê詞另外用檔案記？

2023-06-30 01:55 UTC, a8568730 commented on tox.ini
>      coverage run --source=用字 -m unittest discover -s 試驗/教典名姓
失禮，有名ài巡。我誤會。

2023-06-30 02:48 UTC, sih4sing5hong5 commented on 教典/匯入資料.py
> +            if mia not in ['詞目', '又唸作', '合音唸作', '俗唸作', '詞彙比較', '名']:
Tio̍h，本底就考慮姓siunn濟異用字，就無加，所以新版嘛無加`姓`

2023-06-30 03:01 UTC, sih4sing5hong5 commented on 教典/匯入資料.py
> +                        tsua[hanjiui] not in ['兔', '𠕆', ] and
d5f3504

2023-06-30 03:22 UTC, sih4sing5hong5 commented on 教典/匯入資料.py
> +            if mia not in ['詞目', '又唸作', '合音唸作', '俗唸作', '詞彙比較', '名']:
有加試驗， tī 34a1b55 做好

2023-06-30 03:22 UTC, sih4sing5hong5 commented on 教典/匯入資料.py
> +        yield '𰹬', 'tsn̄g'
有加試驗， tī 34a1b55 做好

2023-07-03 02:23 UTC, a8568730 commented on 教典/匯入資料.py
> +        yield '𰹬', 'tsn̄g'
好

2023-07-03 02:23 UTC, a8568730 commented on 教典/匯入資料.py
> +            if mia not in ['詞目', '又唸作', '合音唸作', '俗唸作', '詞彙比較', '名']:
好

2023-07-03 02:24 UTC, a8568730 commented on 教典/匯入資料.py
> +                        tsua[hanjiui] not in ['兔', '𠕆', ] and
清楚！

2023-07-03 02:25 UTC, a8568730 approved these changes
🎉

2023-07-03 02:25 UTC, merged